HTTP/2 200 
server: nginx/1.18.0
date: Fri, 14 Nov 2025 16:40:45 GMT
content-type: application/sparql-results+xml;charset=utf-8
x-first-solution-millis: 1
x-served-by: wdqs1017
access-control-allow-origin: *
access-control-allow-headers: accept, content-type, content-length, user-agent, api-user-agent
cache-control: public, max-age=300
age: 0
vary: Accept, Accept-Encoding
x-cache: cp1108 miss, cp1108 pass
x-cache-status: pass
server-timing: cache;desc="pass", host;desc="cp1108"
strict-transport-security: max-age=106384710; includeSubDomains; preload
report-to: { "group": "wm_nel", "max_age": 604800, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }
nel: { "report_to": "wm_nel", "max_age": 604800, "failure_fraction": 0.05, "success_fraction": 0.0}
x-client-ip: 24.200.79.107
set-cookie: WMF-Uniq=QCr6G_o2MNSAQqeuDXOLIgKrAAAAAFvdx-HbjhS3IV96cMiA3ffLSRk3zsmBVlcP;Domain=.wikidata.org;Path=/;HttpOnly;secure;SameSite=None;Expires=Sat, 14 Nov 2026 00:00:00 GMT
content-length: 3324
x-request-id: 24915ad5-a265-4971-b6dc-211224f20761
x-analytics: 
